In [1]:
import numpy as np
import pandas as pd

In [2]:
data=[{'Area':2600,'Bedrooms':3,'Age':20,'Price':550000},{'Area':3000,'Bedrooms':4,'Age':15,'Price':565000},
      {'Area':3200,'Age':18,'Price':610000},{'Area':3600,'Bedrooms':3,'Age':30,'Price':595000},
      {'Area':4000,'Bedrooms':5,'Age':8,'Price':760000}]

In [7]:
data=pd.DataFrame(data)

In [8]:
data

Area  Bedrooms  Age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [12]:
import math
med=math.floor(data['Bedrooms'].median())
med

3

In [16]:
data['Bedrooms']=data['Bedrooms'].fillna(med)

In [17]:
data

Area  Bedrooms  Age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [36]:
x=data.drop('Price',axis=1)
y=data['Price']

In [37]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x,y)

LinearRegression()

In [38]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [39]:
reg.intercept_

383725.0

# Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old

In [42]:
reg.predict([[3000,3,40]])

e:\Users\Merin\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [43]:
((137.25*3000)+(-26025.*3)+(-6825.*40)+383725.0)

444400.0

# Find price of home with 2500 sqr ft area, 4 bedrooms, 5 year old

In [44]:
reg.predict([[2500,4,5]])

e:\Users\Merin\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])